services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqldb
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "DB4dmin!"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql       
      - ./init-sql:/init-sql       
    networks:
      - appnet
    restart: always

  personapi-dotnet:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: webapp
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    networks:
      - appnet

volumes:
  sql_data:

networks:
  appnet:
    driver: bridge